//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WickoDemo.Viewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WickoDemo.Viewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUDUSD,12/01/2015 02:00:01.720,0.72613,0.72619
        ///AUDUSD,12/01/2015 02:00:06.237,0.72614,0.72618
        ///AUDUSD,12/01/2015 02:00:06.487,0.72615,0.7262
        ///AUDUSD,12/01/2015 02:00:06.970,0.72612,0.72617
        ///AUDUSD,12/01/2015 02:00:07.220,0.72611,0.72616
        ///AUDUSD,12/01/2015 02:00:07.470,0.7261,0.72615
        ///AUDUSD,12/01/2015 02:00:07.720,0.72611,0.72615
        ///AUDUSD,12/01/2015 02:00:07.970,0.7261,0.72615
        ///AUDUSD,12/01/2015 02:00:09.970,0.72609,0.72614
        ///AUDUSD,12/01/2015 02:00:10.470,0.72611,0.72615
        ///AUDUSD,12/01/2015 02:00:11.970,0.7261,0.72615 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AUDUSD {
            get {
                return ResourceManager.GetString("AUDUSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EURUSD,12/01/2015 02:00:00.720,1.05856,1.05862
        ///EURUSD,12/01/2015 02:00:01.220,1.05855,1.05859
        ///EURUSD,12/01/2015 02:00:01.470,1.05855,1.05858
        ///EURUSD,12/01/2015 02:00:01.720,1.05857,1.05862
        ///EURUSD,12/01/2015 02:00:02.220,1.05855,1.05859
        ///EURUSD,12/01/2015 02:00:02.470,1.05851,1.05856
        ///EURUSD,12/01/2015 02:00:02.720,1.05852,1.05857
        ///EURUSD,12/01/2015 02:00:03.720,1.05851,1.05856
        ///EURUSD,12/01/2015 02:00:04.220,1.05852,1.05856
        ///EURUSD,12/01/2015 02:00:05.220,1.05851,1.05856
        ///EURUSD,12/01/2015 02:00:05.470,1.0585,1.05 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EURUSD {
            get {
                return ResourceManager.GetString("EURUSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GBPUSD,12/01/2015 02:00:00.470,1.5093,1.50937
        ///GBPUSD,12/01/2015 02:00:01.470,1.50932,1.50939
        ///GBPUSD,12/01/2015 02:00:02.470,1.50931,1.50939
        ///GBPUSD,12/01/2015 02:00:02.970,1.50931,1.50938
        ///GBPUSD,12/01/2015 02:00:05.220,1.50933,1.50938
        ///GBPUSD,12/01/2015 02:00:06.237,1.50933,1.50939
        ///GBPUSD,12/01/2015 02:00:06.487,1.50931,1.50939
        ///GBPUSD,12/01/2015 02:00:06.720,1.50931,1.50938
        ///GBPUSD,12/01/2015 02:00:06.970,1.50931,1.50939
        ///GBPUSD,12/01/2015 02:00:09.720,1.50932,1.50941
        ///GBPUSD,12/01/2015 02:00:09.970,1.50932,1.50 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GBPUSD {
            get {
                return ResourceManager.GetString("GBPUSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USDCAD,12/01/2015 02:00:01.220,1.33458,1.33468
        ///USDCAD,12/01/2015 02:00:01.470,1.33458,1.33467
        ///USDCAD,12/01/2015 02:00:01.720,1.33456,1.33465
        ///USDCAD,12/01/2015 02:00:01.970,1.33455,1.33465
        ///USDCAD,12/01/2015 02:00:02.220,1.33456,1.33467
        ///USDCAD,12/01/2015 02:00:06.237,1.33455,1.33464
        ///USDCAD,12/01/2015 02:00:06.487,1.33458,1.33464
        ///USDCAD,12/01/2015 02:00:06.720,1.33459,1.33465
        ///USDCAD,12/01/2015 02:00:06.970,1.33463,1.3347
        ///USDCAD,12/01/2015 02:00:07.220,1.33464,1.33473
        ///USDCAD,12/01/2015 02:00:07.470,1.33469,1.33 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string USDCAD {
            get {
                return ResourceManager.GetString("USDCAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USDCHF,12/01/2015 02:00:00.720,1.02654,1.02662
        ///USDCHF,12/01/2015 02:00:02.220,1.02655,1.02662
        ///USDCHF,12/01/2015 02:00:06.970,1.02654,1.02662
        ///USDCHF,12/01/2015 02:00:12.220,1.02655,1.02662
        ///USDCHF,12/01/2015 02:00:13.220,1.02656,1.02664
        ///USDCHF,12/01/2015 02:00:18.470,1.02655,1.02662
        ///USDCHF,12/01/2015 02:00:18.970,1.02654,1.02661
        ///USDCHF,12/01/2015 02:00:52.720,1.02654,1.0266
        ///USDCHF,12/01/2015 02:01:00.470,1.02654,1.02659
        ///USDCHF,12/01/2015 02:01:08.220,1.02653,1.02659
        ///USDCHF,12/01/2015 02:01:10.720,1.02653,1.02 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string USDCHF {
            get {
                return ResourceManager.GetString("USDCHF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USDJPY,12/01/2015 02:00:00.720,122.927,122.932
        ///USDJPY,12/01/2015 02:00:01.470,122.927,122.931
        ///USDJPY,12/01/2015 02:00:01.970,122.927,122.932
        ///USDJPY,12/01/2015 02:00:05.970,122.927,122.931
        ///USDJPY,12/01/2015 02:00:06.237,122.927,122.932
        ///USDJPY,12/01/2015 02:00:06.487,122.928,122.932
        ///USDJPY,12/01/2015 02:00:06.720,122.93,122.933
        ///USDJPY,12/01/2015 02:00:06.970,122.93,122.935
        ///USDJPY,12/01/2015 02:00:07.470,122.931,122.935
        ///USDJPY,12/01/2015 02:00:11.970,122.932,122.937
        ///USDJPY,12/01/2015 02:00:12.220,122.935,122.9 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string USDJPY {
            get {
                return ResourceManager.GetString("USDJPY", resourceCulture);
            }
        }
    }
}
